package TestLanguage.plugin;

/*Generated by MPS */

import java.util.Comparator;
import java.text.Collator;

/**
 * Comparator for using in SortingModels for ModelInfoItem
 * ModelInfoItems compared as its respective SModel Fully Qualified Names
 */
public class ModelInfoItemComparator implements Comparator<ModelInfoItem> {
  private Collator collator = Collator.getInstance();

  public int compare(ModelInfoItem item, ModelInfoItem item1) {
    String modelName = item.getModel().getModelName().toString();
    String modelName1 = item1.getModel().getModelName().toString();
    int compare = compareString(modelName, modelName1);
    return compare;
  }

  private int compareString(String o1, String o2) {
    return collator.compare(o1, o2);
  }
}
