package TestLanguage.plugin;

/*Generated by MPS */

import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import java.awt.Frame;
import javax.swing.JDialog;
import jetbrains.mps.progress.ProgressMonitorAdapter;
import java.util.HashSet;
import org.jetbrains.mps.openapi.model.SModel;

/**
 * Listener interface for passing through modal windows/frames/dialogs
 * Holds a lot of information in actionPerformed signature
 */
public abstract class ModelsSelectionActionListener {
  public abstract void actionPerformed(final AnActionEvent event, final Map<String, Object> _params, Frame mpsBaseFrame, JDialog ownerDialog, ProgressMonitorAdapter monitor, HashSet<SModel> approvedModels);



  public ModelsSelectionActionListener() {
  }
}
