package TestLanguage.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import jetbrains.mps.logging.Logger;

public class TestGroup_ActionGroup extends GeneratedActionGroup {
  private static Logger LOG = Logger.getLogger(TestGroup_ActionGroup.class);
  public static final String ID = "TestLanguage.plugin.TestGroup_ActionGroup";

  public TestGroup_ActionGroup() {
    super("TestGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    try {
      TestGroup_ActionGroup.this.addAction("TestLanguage.plugin.TestAction_Action");
    } catch (Throwable t) {
      LOG.error("User group error", t);
    }
  }
}
